#version=1.6
include:
   - project: 'pub/mrt_build_config'
     ref: master
     file: '/ci_templates/default_catkin_project.yml'

deps:
# we only test one single dependency. Otherwise this would test hundreds of packages.
  script:
  - mrt ci test_deps -f --no-status -i example_package_ros_tool --only --release $CI_PROJECT_NAME
